#!/bin/bash
set -eo pipefail

DOCKER_IMAGE="mozmeao/slack-notify-script:latest"
docker pull "$DOCKER_IMAGE"
docker run --rm \
           --env SLACK_CHANNEL=basket \
           --env SLACK_TOKEN \
           --env CI_PROJECT_NAME \
           --env CI_PIPELINE_URL \
           --env CI_COMMIT_BRANCH \
           "$DOCKER_IMAGE" "$@"
