apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: basket-admin-stage
    type: web
  name: basket-admin-stage-web
  namespace: basket-admin-stage
spec:
  progressDeadlineSeconds: 600
  replicas: 0
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: basket-admin-stage
      type: web
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: basket-admin-stage
        type: web
        heritage: deis
      name: basket-admin-stage-web
      namespace: basket-admin-stage
    spec:
      imagePullSecrets:
        - name: dockerhub-registry
      containers:
      - args:
        - bin/run-prod.sh
        command:
        - /bin/bash
        - -c
        env:
        - name: ADMIN_ONLY_MODE
          value: "True"
        - name: ALLOWED_HOSTS
          value: "*"
        - name: CELERY_ALWAYS_EAGER
          value: "False"
        - name: CLUSTER_NAME
          value: "mozmeao-or"
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: database-url
              name: basket-admin-stage-secrets
        - name: DEBUG
          value: "False"
        - name: EMAIL_HOST
          valueFrom:
            secretKeyRef:
              key: email-host
              name: basket-admin-stage-secrets
        - name: EMAIL_HOST_PASSWORD
          valueFrom:
            secretKeyRef:
              key: email-host-password
              name: basket-admin-stage-secrets
        - name: EMAIL_HOST_USER
          valueFrom:
            secretKeyRef:
              key: email-host-user
              name: basket-admin-stage-secrets
        - name: EMAIL_PORT
          value: "587"
        - name: EMAIL_USE_TLS
          value: "True"
        - name: ENFORCE_HOSTNAME
          value: admin-stage.basket.moz.works
        - name: K8S_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: K8S_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MAINTENANCE_MODE
          value: "True"
        - name: MAINTENANCE_READ_ONLY
          value: "True"
        - name: NEWRELIC_INI_FILE
          value: newrelic.ini
        - name: NEW_RELIC_APP_NAME
          value: basket-admin-stage-mozmeao-or
        - name: NEW_RELIC_CONFIG_FILE
          value: /app/newrelic.ini
        - name: NEW_RELIC_LICENSE_KEY
          valueFrom:
            secretKeyRef:
              key: new-relic-license-key
              name: basket-admin-stage-secrets
        - name: OIDC_ENABLE
          value: "True"
        - name: OIDC_OP_AUTHORIZATION_ENDPOINT
          value: https://auth.mozilla.auth0.com/authorize
        - name: OIDC_OP_TOKEN_ENDPOINT
          value: https://auth.mozilla.auth0.com/oauth/token
        - name: OIDC_OP_USER_ENDPOINT
          value: https://auth.mozilla.auth0.com/userinfo
        - name: OIDC_RP_CLIENT_ID
          valueFrom:
            secretKeyRef:
              key: oidc-rp-client-id
              name: basket-admin-stage-secrets
        - name: OIDC_RP_CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              key: oidc-rp-client-secret
              name: basket-admin-stage-secrets
        - name: PORT
          valueFrom:
            secretKeyRef:
              key: port
              name: basket-admin-stage-secrets
        - name: REDIS_CACHE_DB
          value: "3"
        - name: REDIS_CELERY_DB
          value: "2"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              key: redis-url
              name: basket-admin-stage-secrets
        - name: SAML_CREATE_USER
          value: "False"
        - name: SAML_ENABLE
          value: "True"
        - name: SAML_ENTITY_ID
          value: basket-admin-stage.us-west.moz.works/saml2/metadata/
        - name: SAML_REMOTE_METADATA
          value: stage.xml
        - name: SAML_SSO_URL
          value: https://basket-admin-stage.us-west.moz.works/saml2/acs/
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              key: secret-key
              name: basket-admin-stage-secrets
        - name: SECURE_SSL_REDIRECT
          value: "True"
        - name: SENTRY_DSN
          valueFrom:
            secretKeyRef:
              key: sentry-dsn
              name: basket-admin-stage-secrets
        - name: SFDC_PASSWORD
          valueFrom:
            secretKeyRef:
              key: sfdc-password
              name: basket-admin-stage-secrets
        - name: SFDC_SEC_TOKEN
          valueFrom:
            secretKeyRef:
              key: sfdc-sec-token
              name: basket-admin-stage-secrets
        - name: SFDC_USERNAME
          valueFrom:
            secretKeyRef:
              key: sfdc-username
              name: basket-admin-stage-secrets
        - name: STATSD_CLIENT
          value: django_statsd.clients.normal
        - name: STATSD_PREFIX
          value: basket-admin-stage
        - name: SUBHUB_OPP_RECORD_TYPE
          value: 0124O000000R0ODQA0
        - name: SYNC_KEY
          valueFrom:
            secretKeyRef:
              key: sync-key
              name: basket-admin-stage-secrets
        - name: TASK_LOCKING_ENABLE
          value: "True"
        - name: WSGI_NUM_WORKERS
          value: "4"
        image: mozmeao/basket:f0dda2fb
        imagePullPolicy: IfNotPresent
        name: basket-admin-stage-web
        readinessProbe:
          failureThreshold: 1
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 8000
          timeoutSeconds: 5
        resources:
          limits:
            cpu: "1"
            memory: 1200Mi
          requests:
            cpu: 250m
            memory: 600Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
