apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-04-19T08:52:45Z
  labels:
    app: basket-admin-stage
  name: basket-nodeport
  namespace: basket-admin-stage
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31906
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: basket-admin-stage
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
