apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: basket-prod
  name: basket-nodeport
  namespace: basket-prod
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 32162
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: basket-prod
    type: web
  sessionAffinity: None
  type: NodePort
