apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2018-04-19T08:51:28Z
  labels:
    app: basket-admin
  name: basket-nodeport
  namespace: basket-admin
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: http
    nodePort: 31973
    port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: basket-admin
    type: web
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
